### ISSUE TITLE
cannot hit oauth/request_token endpoint

### ISSUE THREAD

**Issue by EricWVGG** [mw99/OhhAuth#5]
I am attempting to use OhhAuth to calculate signatures with the Vapor server-side library. It's working pretty well, for example here where I'm doing a simple username search:
```swift
let path = URL(string:"https://api.twitter.com/1.1/users/search.json"),
var headers = HTTPHeaders()
var signature = OhhAuth.calculateSignature(
    url: path, 
    method: "GET", 
    parameter: ["q" : keywords], 
    consumerCredentials: self.consumerCredentials, 
    userCredentials: self.userCredentials
    )
headers.replaceOrAdd(name: .authorization, value: signature)
_ = try container.client().get("\(path)?q=\(escapedKeywords)", headers: headers).map { response -> Void in
  // hooray
```

The process for getting a request_token, as far as I can tell, has two differences: userCredentials is nil (we're trying to get them), the parameter is a percent-escaped callback, and the signature has an oauth_callback parameter in there. (and it's POST instead of GET, nabd)

I've tried many variations on this request and always get "unauthorized" from Twitter. Am I overlooking something stupid?
```swift
var signature = OhhAuth.calculateSignature(
    url: path,
    method: "POST",
    parameter: ["oauth_callback": "http%3A%2F%2Flocalhost%3A3000%2Fcallback%2Ftwitter"],
    consumerCredentials: self.consumerCredentials,
    userCredentials: nil
)
signature = signature + ",oauth_callback=\"http%3A%2F%2Flocalhost%3A3000%2Fcallback%2Ftwitter\""
```

**Comment by mw99** [comment]
Hmn... kinda sorry but OhhAuth does not support the `oauth_callback`. Would probably be time for an update but I'm too busy at the moment and twitter banned all my test accounts...

But is would not be very hard to add an extra oauth_ parameter by yourself. In file https://github.com/mw99/OhhAuth/blob/master/Sources/OhhAuth.swift after 135, can you just add 

```
"oauth_callback": "http://your-unencoded-url...."
```
as a hard coded parameter and try again? And do not just add something to the signature string like:
```
signature = signature + "...something..."
```
oauth parameters have to be in the correct order alphabetically and be part of the signature calculation from the start. Sorry that's the best I can do for you at the moment.

**Comment by EricWVGG** [comment]
Hmm that does sound like something I could potentially do. I will give it a crack. Thank you for the advice and building this in the first place, otherwise it is working very well. 

/thumbs

**Comment by EricWVGG** [comment]
Did it. https://github.com/EricWVGG/OhhAuth

I feel like the code around 78-80 is a little janky, but it works for my purposes.

I am only using the calculateSignature() method, so am not able to test this with the rest of your library. Note that Credentials now has Secret as an optional, because requests to acquire an access token take the request token but have no corresponding secret. This will probably be a breaking change elsewhere in your package. 

Thank you again for pointing me in the right direction.

**Comment by mw99** [comment]
Oh very cool. Glad that it worked out for you. Will try to support `oauth_callback` some day. Have a nice day. Thanks for sharing back.
